Add missing utility function

diff --git a/mount-fs b/mount-fs
--- a/mount-fs
+++ b/mount-fs
@@ -41,6 +41,16 @@ usage_and_exit() {
     exit 1
 }
 
+
+exec_cmd() {
+    eval "$*"
+    if [[ $? -ne 0 ]]
+    then
+        echo "Could not execute command: $*"
+        exit 1
+    fi
+}
+
 #################
 ## Validations ##
 #################
